- JWT_SECRET
- JWT_REFRESH_SECRET
- BACKUP_ENCRYPTION_KEY
- SENTRY_DSN
- REDIS_PASSWORD
- DATABASE_URL
# LLM provider keys removed from required list — provider keys optional and should be managed outside the repo
