name: ci
on:
  push:
    branches: [main, fix/*, feat/*]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (root)
        run: npm ci

      - name: Install deps (backend) & build
        run: npm --prefix backend ci && npm --prefix backend run build

      - name: Lint & Typecheck
          # Se ejecuta en Ubuntu (bash) en CI: usar '&&' está bien aquí
        run: npm run lint && npm run type-check

      - name: Unit/Integration
        run: npm run test:ci -- --maxWorkers=1 --no-file-parallelism

      - name: Contract tests
        run: npm run test:contract

      - name: E2E
        run: npm run test:e2e

      - name: Security scans
        run: |
          gitleaks detect --no-banner
          trivy fs . --scanners vuln,secret --severity HIGH,CRITICAL
          npm audit --production

      - name: Build frontend
        run: npm run build

      - name: Start backend for perf smoke
        run: |
          npm --prefix backend run start &
          npx wait-on http://localhost:3001/api/health --timeout 60000

      - name: Performance smoke (API)
        run: npm run perf:api
        env:
          BASE_URL: http://localhost:3001

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            coverage/**
            playwright-report/**
            dist/**
            gitleaks.sarif
            trivy.sarif
            lhci-report/**
